package net.imglib2.vigra;

import java.io.IOException;
import java.net.URL;
import java.util.Properties;

/**
 * A helper to load the library generated by the nar-maven-plugin.
 * 
 * @author Johannes Schindelin
 */
public class NarHelper {

	/**
	 * Loads the library compiled by the nar-maven-plugin.
	 * 
	 * @param clazz a class compiled into the same project as the library
	 * @param groupId the groupId of the project
	 * @param artifactId the artifactId of the project
	 */
	public static void loadLibrary(final Class<?> clazz, final String groupId, final String artifactId) {
		final String osName = System.getProperty("os.name").toLowerCase();
		String libPrefix = "lib";
		final String libSuffix;
		if (osName.startsWith("mac")) {
			libSuffix = ".dylib";
		} else if (osName.startsWith("win")) {
			libPrefix = "";
			libSuffix = ".dll";
		} else {
			libSuffix = ".so";
		}

		final String propertiesPath = "/META-INF/nar/" + groupId + "/" + artifactId + "/nar.properties";
		final URL url = clazz.getResource(propertiesPath);
		if (url != null) try {
			final Properties props = new Properties();
			props.load(url.openStream());
			String output = props.getProperty("output"), aol = null, libName = null;
			for (final Object key : props.keySet()) {
				final String name = (String)key;
				if (name.endsWith(".output")) {
					aol = name.substring(0, name.length() - ".output".length());
					libName = props.getProperty(name);
				}
			}
				if (output == null || aol == null || libName == null) {
					throw new UnsatisfiedLinkError(
							"Could not determine name of native library: "
									+ output + ":" + aol + ":" + libName);
			}
			final String urlString = url.toString();
			final String libPath;
			if (urlString.startsWith("file:")) {
				String path = urlString.substring(5, urlString.length() - propertiesPath.length());
				if (path.endsWith("/classes")) path = path.substring(0, path.length() - 8);
				libPath = path + "/nar/" + libName + "-" + aol + "-jni/lib/" + aol + "/jni/" + libPrefix + libName + libSuffix;
			} else {
				throw new UnsatisfiedLinkError("Could not load native library: URL of .jar is " + urlString);
			}
			System.load(libPath);
		} catch (IOException e) {
			e.printStackTrace();
			throw new UnsatisfiedLinkError("Could not find native library");
		}
	}

}
